<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PreSelectShippingPayment
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Multi Shipping Checkout Template
 *
 * @var  $block  Bss\PreSelectShippingPayment\Block\ConfigMenthod
 *
 */  ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_PreSelectShippingPayment/js/checkout_process": {
                "defaultShipping": "<?php echo $block->escapeHtml($block->getShippingDefault()); ?>",
                "defaultPayment" : "<?php echo $block->escapeHtml($block->getPaymentDefault());?>",
                "positionShipping" : "<?php echo $block->escapeHtml($block->getShippingPosition()); ?>",
                "positionPayment" : "<?php echo $block->escapeHtml($block->getPaymentPosition()); ?>"
            }
        }
    }
</script>
